# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import products_pb2 as products__pb2


class ProductsStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecord = channel.unary_unary(
        '/product.Products/GetRecord',
        request_serializer=products__pb2.Id.SerializeToString,
        response_deserializer=products__pb2.Record.FromString,
        )
    self.ListRecords = channel.unary_stream(
        '/product.Products/ListRecords',
        request_serializer=products__pb2.AllRecords.SerializeToString,
        response_deserializer=products__pb2.Record.FromString,
        )


class ProductsServicer(object):
  """Interface exported by the server.
  """

  def GetRecord(self, request, context):
    """A simple RPC.                                                              
    Obtains the record at a given position.
    A Record with an empty info is returned if there's no record found in db.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListRecords(self, request, context):
    """A server-to-client streaming RPC.                                       

    Obtains the Records available within the given criteria.  Results are 
    streamed rather than returned at once (e.g. in a response message with a
    repeated field).                                                
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecord,
          request_deserializer=products__pb2.Id.FromString,
          response_serializer=products__pb2.Record.SerializeToString,
      ),
      'ListRecords': grpc.unary_stream_rpc_method_handler(
          servicer.ListRecords,
          request_deserializer=products__pb2.AllRecords.FromString,
          response_serializer=products__pb2.Record.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'product.Products', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
